workload:
  image:
    repository: "quay.io/jetstack/cert-manager-cainjector"
    tag: "v1.18.2"
  args:
  - '--v=2'
  - '--leader-elect'
  - '--leader-election-lease-duration=15s'
  - '--leader-election-renew-deadline=10s'
  - '--leader-election-retry-period=2s'
  - '--leader-election-namespace=$(POD_NAMESPACE)'
  - '--logging-format=json'
  - '--metrics-listen-address=0.0.0.0:9100'
  probes:
    readinessProbe:
      path: "/metrics"
      port: http-metrics
    livenessProbe:
      path: "/metrics"
      port: http-metrics
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "192Mi"
      limits:
        memory: "192Mi"
  priorityClassName: "application-critical"
  securityContext:
    readOnlyRootFilesystem: true
service:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9100
rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
      - apiGroups: ["cert-manager.io"]
        resources: ["certificates"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["get", "create", "update", "patch"]
      - apiGroups: ["admissionregistration.k8s.io"]
        resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: ["apiregistration.k8s.io"]
        resources: ["apiservices"]
        verbs: ["get", "list", "watch", "update", "patch"]
      - apiGroups: ["apiextensions.k8s.io"]
        resources: ["customresourcedefinitions"]
        verbs: ["get", "list", "watch", "update", "patch"]
    role:
      rules:
      # Used for leader election by the controller
      # cert-manager-cainjector-leader-election is used by the CertificateBased injector controller
      #   see cmd/cainjector/start.go#L113
      # cert-manager-cainjector-leader-election-core is used by the SecretBased injector controller
      #   see cmd/cainjector/start.go#L137
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        resourceNames: ["cert-manager-cainjector-leader-election", "cert-manager-cainjector-leader-election-core"]
        verbs: ["get", "update", "patch"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["create"]
