service:
  enabled: false
  type: "NodePort"

certificate:
  enabled: true
  spec:
    secretName: "letsencrypt-wildcard-certificate"
    dnsNames:
    - 'projectwhitebox.com'
    - '*.projectwhitebox.com'
    issuerRef:
      name: "istio-ingress-gateway"
      kind: Issuer
issuer:
  enabled: true
  type: Issuer
  spec:
    acme:
      email: "jamiestinson1@icloud.com"
      solvers:
      - dns01:
          cloudflare:
            email: "jamiestinson1@icloud.com"
            apiTokenSecretRef:
              name: cloudflare
              key: API_TOKEN
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-acme-key

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: cloudflare
      namespace: istio
    spec:
      encryptedData:
        API_TOKEN: AgBo4mPx7R9f7lbfRvgN8pKuNthieQATyCWjXwvZfnYbQVSuY2XcIZ1q9bKKS1mZChvO8TCwqtf5U60zSxTeHjw3X6fv8tCv10Gi47NtQyVF9WAtsAFoiycE29qwSHR4PLgIRSoBZC35rlK7FHJx7c3E52kR3P+//rYmZ543C6+zzmHlL+gtD3Y1Cnr5jrChnPduKWnvgG5TGJ7hPB867q5mBXRaiv4M+cEI9klqFo1/IBtRrFAKa5yJePy6vzaQGewn3/YILbfSCP3QbyZ/56TuK1ioRUwxr3YfCaC2v0GG0ONajjCf8KY7JoeRkkLlthjDQb4zV47HCYO4kS6b+UWicT+9vq1H99GZl/iamMSyhyYnbttsmECFkWiS8X0OoKWe/1EUAslFl0XOrk8KaFLhIS7/SNqm1ZAAUuLJ0fy0ApUBFnlXtBeUWomt22MmdVnxSDB/HDGOoYXf7oTuHJjrr8eW889aGfIrCtz2egLdFKxv0Z6ADSOkTYT9v8OCs+oGCFOPeFRfXWLAiFx0u0vzqNFmJVDczmWLuZeHC+OYiv0jysQPPSSIZYXKbhXz5SSWpfefXRFgG1udqmnYVZqAKcfRT87vREdpWb36034XLpaXf3Zc1itnrWacZmnrhWK+Ag0CfKTQTX3yaQ7Y8Ckf9DS216RvCFXzThTp0YFMlGtI3D2FDjvIOKneyn1TNMBN1JecbOWAFOlPD9X3XII6zUQpAD1nB6blLOejVx7gfMxcAnOmIcRS
      template:
        metadata:
          name: cloudflare
          namespace: istio
        type: Opaque
  - |
    apiVersion: networking.istio.io/v1beta1
    kind: Gateway
    metadata:
      name: external
      namespace: istio
    spec:
      selector:
        istio: ingress-gateway
      servers:
      - port:
          number: 443
          name: https
          protocol: HTTPS
        tls:
          mode: SIMPLE
          credentialName: letsencrypt-wildcard-certificate
        hosts:
        - "*.projectwhitebox.com"

workload:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false
