service:
  type: "NodePort"

ingressClass:
  enabled: true
  isDefault: false
  controller: "istio.io/ingress-controller"

certificate:
  enabled: true
  spec:
    secretName: "letsencrypt-wildcard-certificate"
    dnsNames:
    - 'projectwhitebox.com'
    - '*.projectwhitebox.com'
    issuerRef:
      name: "istio-ingress-gateway"
      kind: Issuer
issuer:
  enabled: true
  type: Issuer
  spec:
    acme:
      email: "jamiestinson1@icloud.com"
      solvers:
      - dns01:
          cloudflare:
            email: "jamiestinson1@icloud.com"
            apiTokenSecretRef:
              name: cloudflare
              key: API_TOKEN
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-acme-key

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: cloudflare
      namespace: istio
    spec:
      encryptedData:
        API_TOKEN: AgBYOzWnVsdN8YRZKwZ/8Spm3A/ptvKlIzHcZDHqo2ttFMqH1sfe4ooSDkcb6/DacXmcU+O0Q3u28WIBlJ5A2Vfwg9iLUSySPfih3P9pjQhJ9mdJbQcdwL2kqEPb2+KN0C2fLy7cSEkFqw6gpW8sJQs5k+xD2YLKx/Qi8zhFEoHddXNAw+wws6X+04lGDF9/07H71spDklZu+S2DpCE9h2Li0m9XFqNc3ULmUuV+Ewz0saoMZy+xrzOULcYgmQ1nlyWE8l9vliCZ5BbnwKje7ANVayXcB9NtHJSXKeWmj6b5yF80SX5exQSalb7C0Or6NGTPhSBjhiU2xg9WUPz5vS6PfLq33fxvLTnkRNPdaXjXj3DUdpmcAYcvhbS3gpaVdTPCUtNKsfQLOUUSQymi6kjShB7rJdmknIf7Iwg8DOZ/tKpwjckuEfpOV/qGuAMAB1tEE30BKDJO2sCL1l6AWMHCQ7kIiDA2hIPQYQA4iJSCwQftufYhEPWUu5hyV8lvxZLWi+6GCJDSp6iq+8xBWFdzQI1TAznAJDN8st1L5tfWNDVY3saW2liLWwsAFA7tvb/nXWOBrwcf7DEEu+jUmXKUOQRhL8f+elxKmYkLmbZzKrV+dfOXAO0/EFfB5lhwj6+FUm51KjDRkOfx4p+Ez/LZm+OwUsxVfSOLHJurbBuie4F0OavL6Kp9Eanz7bh3r14MAZ+AJ7pXzo4GgUnwhaBdVwKdvypYjdemt2+LUq2JFlkfOKmX+xtg
      template:
        metadata:
          name: cloudflare
          namespace: istio
        type: Opaque
