workload:
  type: "StatefulSet"
  image:
    registry: "ghcr.io"
    repository: henriquesebastiao/downtify
    tag: 1.1.1
  strategy:
    type: OnDelete
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "1Gi"
        ephemeral-storage: "2Gi"
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8000
    livenessProbe:
      type: tcpSocket
      port: 8000
  storage:
    - name: downtify-music
      type: pvc
      mountPath: /downloads
      claimName: "downtify-music"

service:
  ports:
    - name: http
      port: 8000
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: music.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "downtify"
          port: 8000

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: downtify-music
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/hdd-pool/music"
      mountOptions:
        - nfsvers=4.1 
        - hard
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - async
        - nconnect=8
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: downtify-music
      namespace: downtify
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: downtify-music
