workload:
  type: "DaemonSet"
  image:
    repository: "docker.io/timberio/vector"
    tag: "0.48.0-distroless-libc"
  envsFromField:
    - name: "VECTOR_SELF_NODE_NAME"
      fieldPath: spec.nodeName
  probes: {}
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "4Gi"
        ephemeral-storage: "16Mi"
      limits:
        memory: "4Gi"
        ephemeral-storage: "16Mi"
  storage:
  - name: var-log
    type: hostPath
    mountPath: /var/log
    hostPath: /var/log
    readOnly: true
  - name: var-lib
    type: hostPath
    mountPath: /var/lib
    hostPath: /var/lib
    readOnly: true
  # - name: var-lib-vl-connector
  #   type: hostPath
  #   mountPath: /vl-collector
  #   hostPath: /var/lib/vl-connector
  #   readOnly: false
  - name: config
    type: configMap
    mountPath: /etc/vector
    configMapName: victoria-logs-collector
configMap:
  enabled: true
  configMaps:
  - name: "victoria-logs-collector"
    data:
      vector.yaml: |
        data_dir: /vl-collector

        sources:
          k8s:
            type: kubernetes_logs
            pod_annotation_fields:
              # Disable "pod_ips" as "pod_ip" already includes required info
              pod_ips: ""

        transforms:
          json_parser:
            type: remap
            inputs: [k8s]
            source: |
              .message = parse_json(.message) ?? .message

        sinks:

          remote_write_0:
            type: http
            inputs: [json_parser]
            uri: "http://victoria-logs:9428/insert/jsonline"
            encoding:
              codec: json
            framing:
              method: newline_delimited
            healthcheck:
              enabled: false
            request:
              headers:
                AccountID: "0"
                ProjectID: "0"
                VL-Stream-Fields: kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
                VL-Msg-Field: message
                VL-Time-Field: timestamp
            compression: "zstd"

service:
  enabled: false

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
      - apiGroups:
          - ''
        resources:
          - nodes
          - namespaces
          - pods
        verbs:
          - get
          - list
          - watch
