{
 "title": "Kubernetes / Image Cache",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_image_keeper_controller_up{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_image_keeper_proxy_build_info{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Images Expiring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{expiring=\"true\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Images in Registry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{cached=\"true\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Images Not In Registry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{cached=\"false\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Failing Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(status) (sum by(status, instance) (kube_image_keeper_controller_containers_with_cached_image{status!~\"Ready|Pulling\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CachedImages count per status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(status) (sum by(status, instance) (kube_image_keeper_controller_cached_images{ status!=\"Synchronizing\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proxies Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statusCode) (kube_image_keeper_proxy_http_requests_total{ cacheHit=\"true\", statusCode=\"200\"}) / sum by(statusCode) (kube_image_keeper_proxy_http_requests_total{ statusCode=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (kube_image_keeper_controller_containers_with_cached_image{cached=\"true\"}) / count(kube_pod_container_info{})",
     "legendFormat": "Rewritten by Kuik"
    },
    { "expression": "1 - $A", "type": "math" }
   ]
  },
  {
   "title": "Image put in cache",
   "type": "timeseries",
   "description": "Images put in cache by controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(kube_image_keeper_controller_image_put_in_cache_total{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Images removed from cache",
   "type": "timeseries",
   "description": "Image removed from cache by controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(kube_image_keeper_controller_image_removed_from_cache_total{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful cached images by source registries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(upstream_registry) (increase(kube_image_keeper_controller_image_caching_request{ successful=\"true\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful cached images by source registries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(upstream_registry) (increase(kube_image_keeper_controller_image_caching_request{successful=\"false\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(statusCode) (increase(kube_image_keeper_proxy_http_requests_total{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests to local registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"true\"}[$__rate_interval]))",
     "legendFormat": "Requests total"
    }
   ]
  },
  {
   "title": "Requests to source registries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"false\"}[$__rate_interval]))",
     "legendFormat": "Requests total"
    }
   ]
  },
  {
   "title": "Requests to local registry (by source registries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(registry) (increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"true\"}[$__rate_interval]))",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Requests to source registries (by source registries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(registry) (increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"false\"}[$__rate_interval]))",
     "legendFormat": "{{registry}}"
    }
   ]
  }
 ]
}