workload:
  image:
    repository: ghcr.io/jmcgrath207/k8s-ephemeral-storage-metrics
    tag: 1.18.1
  probes:
    readinessProbe:
      type: tcpSocket
      port: 9100
    livenessProbe:
      type: tcpSocket
      port: 9100
  envs:
    - name: DEPLOY_TYPE
      value: "Deployment"
    - name: SCRAPE_INTERVAL
      value: "15"
    - name: MAX_NODE_CONCURRENCY
      value: "10"
    - name: CLIENT_GO_QPS
      value: "5"
    - name: CLIENT_GO_BURST
      value: "10"
    - name: LOG_LEVEL
      value: "info"
    - name: EPHEMERAL_STORAGE_POD_USAGE
      value: "true"
    - name: EPHEMERAL_STORAGE_NODE_AVAILABLE
      value: "true"
    - name: EPHEMERAL_STORAGE_NODE_CAPACITY
      value: "true"
    - name: EPHEMERAL_STORAGE_NODE_PERCENTAGE
      value: "true"
    - name: EPHEMERAL_STORAGE_CONTAINER_LIMIT_PERCENTAGE
      value: "true"
    - name: EPHEMERAL_STORAGE_CONTAINER_VOLUME_USAGE
      value: "true"
    - name: EPHEMERAL_STORAGE_CONTAINER_VOLUME_LIMITS_PERCENTAGE
      value: "true"
    - name: EPHEMERAL_STORAGE_INODES
      value: "true"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "50m"
        memory: "128Mi"
        ephemeral-storage: "512Mi"
      limits:
        memory: "128Mi"
        ephemeral-storage: "512Mi"
service:
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups: [""]
          resources: ["nodes","nodes/proxy", "nodes/stats", "pods"]
          verbs: ["get","list", "watch"]
