workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

configmapReload:
  prometheus:
    enabled: false

server:
  name: "prometheus"
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  retention: "2h"
  persistentVolume:
    size: 25Gi
    storageClass: "openebs"
  statefulSet:
    enabled: true
    pvcDeleteOnStsDelete: true
    pvcDeleteOnStsScale: true
  resources:
    requests:
      cpu: "10m"
      memory: "4Gi"
      ephemeral-storage: "16Mi"
    limits:
      memory: "4Gi"
      ephemeral-storage: "16Mi"

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

extraObjects:
  - |
    apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: prometheus
      namespace: prometheus
    spec:
      hosts:
      - "prometheus.projectwhitebox.com"
      gateways:
      - istio/external
      http:
      - match:
        - uri:
            prefix: /
        route:
        - destination:
            host: prometheus-prometheus.prometheus.svc.cluster.local
            port:
              number: 80
