# autoPatching:
#   enabled: true
#   annotations:
#     argocd-image-updater.argoproj.io/image-list: "prometheus=quay.io/prometheus/prometheus:~v3, thanos=quay.io/thanos/thanos:~v0"
#     argocd-image-updater.argoproj.io/thanos.force-update: "true"
#     argocd-image-updater.argoproj.io/thanos.helm.image-spec: "workload.extraContainers[0].image"
#     argocd-image-updater.argoproj.io/thanos.update-strategy: "semver"
workload:
  type: StatefulSet
  image:
    repository: quay.io/prometheus/prometheus
    tag: v3.4.2
  args:
  - '--config.file=/etc/config/prometheus.yaml'
  - '--web.console.libraries=/etc/prometheus/console_libraries'
  - '--web.console.templates=/etc/prometheus/consoles'
  - '--web.enable-lifecycle'
  - '--web.enable-admin-api'
  - "--storage.tsdb.no-lockfile"
  - "--storage.tsdb.min-block-duration=2h"
  - "--storage.tsdb.max-block-duration=2h"
  - '--storage.tsdb.path=/prometheus'
  envsSecret:
  - name: OBJSTORE_CONFIG
    secret: thanos
    key: thanos.yaml
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "4Gi"
        ephemeral-storage: "16Mi"
      limits:
        memory: "4Gi"
        ephemeral-storage: "16Mi"
  probes:
    readinessProbe:
      path: "/-/ready"
      port: 9090
    livenessProbe:
      path: "/-/healthy"
      port: 9090
  storage:
  - name: config
    type: configMap
    mountPath: /etc/config
    configMapName: prometheus
  - name: prometheus-data
    type: pvcTemplate
    mountPath: /prometheus
    accessModes:
    - "ReadWriteOnce"
    storageClass: "openebs"
    size: "25Gi"
    readOnly: false
  extraContainers:
  - name: thanos
    image: "quay.io/thanos/thanos:v0.38.0"
    ports:
    - containerPort: 9091
      name: grpc
      protocol: TCP
    - containerPort: 10902
      name: http
      protocol: TCP
    env:
    - name: OBJSTORE_CONFIG
      valueFrom:
        secretKeyRef:
          key: thanos.yaml
          name: thanos
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    args:
    - 'sidecar'
    - '--objstore.config=$(OBJSTORE_CONFIG)'
    - '--tsdb.path=/prometheus'
    - '--prometheus.url=http://localhost:9090'
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/ready
        port: 10902
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/healthy
        port: 10902
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    volumeMounts:
    - name: config
      mountPath: /etc/config
    - name: prometheus-data
      mountPath: /prometheus
service:
  clusterIP: "None"
  ports:
  - name: http
    port: 9090
    protocol: TCP
  - name: grpc
    port: 10901
    protocol: TCP
configMap:
  enabled: true
  configMaps:
  - name: "prometheus"
    data:
      prometheus.yaml: |
        global:
          scrape_interval: 5s
          evaluation_interval: 5s
          external_labels:
            cluster: prometheus-ha
            replica: ${POD_NAME}

        scrape_configs:
          # Scraper for Kubernetes services with HTTP metrics
          - job_name: 'kube-http-services'
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: http-metrics
                action: keep
              - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
                target_label: service
                separator: /
                replacement: $1/$2
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: instance
              - action: labeldrop
                regex: __meta_kubernetes.*

          # Scraper for Kubernetes services with HTTPS metrics
          - job_name: 'kube-https-services'
            scheme: https
            tls_config:
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: https-metrics
                action: keep
              - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
                target_label: service
                separator: /
                replacement: $1/$2
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: instance
              - action: labeldrop
                regex: __meta_kubernetes.*

          # Scraper for kubernetes api server
          - job_name: "kube-apiserver"
            scheme: https
            metrics_path: /metrics
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_name]
                regex: .*controlplane.*
                action: keep
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:6443
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          # Scraper for kubernetes proxy
          - job_name: "kube-proxy"
            scheme: http
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:10249
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          # Scraper for kubernetes controller manager
          - job_name: "kube-controller-manager"
            scheme: https
            metrics_path: /metrics
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_name]
                regex: .*controlplane.*
                action: keep
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:10257
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          # Scraper for kubernetes scheduler
          - job_name: "kube-scheduler"
            scheme: https
            metrics_path: /metrics
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_name]
                regex: .*controlplane.*
                action: keep
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:10259
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          # Scraper for cadvisor
          - job_name: "kube-cadvisor"
            scheme: https
            metrics_path: /metrics/cadvisor
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)

          # Kubelet
          - job_name: "kubelet"
            scheme: https
            metrics_path: /metrics
            authorization:
              type: Bearer
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)

          # Scraper for kubernetes etcd cluster
          - job_name: "etcd"
            scheme: http
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_name]
                regex: .*controlplane.*
                action: keep
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:2381
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          # Scraper for containerd
          - job_name: "containerd"
            scheme: http
            metrics_path: /v1/metrics
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                replacement: ${1}:11234
                target_label: __address__
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance

          - job_name: 'postgres-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_name]
                regex: '.*postgres.*'
                action: keep

              - source_labels: [__meta_kubernetes_pod_container_port_number]
                regex: '9187'
                action: keep

              - source_labels: [__meta_kubernetes_pod_ip]
                target_label: __address__
                replacement: '$1:9187'

              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
      - apiGroups:
        - ''
        resources:
        - nodes
        - nodes/proxy
        - nodes/metrics
        - services
        - endpoints
        - pods
        - ingresses
        - configmaps
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - extensions
        - networking.k8s.io
        resources:
        - ingresses/status
        - ingresses
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - discovery.k8s.io
        resources:
        - endpointslices
        verbs:
        - get
        - list
        - watch
      - nonResourceURLs:
        - /metrics
        verbs:
        - get
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
  - host: prometheus.projectwhitebox.com
    path: /
    pathType: "Prefix"
    tls:
      enabled: false
    backend:
      service:
        name: "prometheus"
        port: 9090
extraObjects:
- |
  apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    name: thanos
    namespace: thanos
  spec:
    encryptedData:
      thanos.yaml: AgCBKs/ujEFhtKCekR5/6xmPYg78FAe4k168QubmWjMs/TehYTSjHFU9coe8t8kE7J72shXbtn4+u4M4Hg/rAT7G6QI+4W0J+Jxv8XBVOzZ5bREiLcvd/UbR1cn38dkbc9ssZRzBo9kx/F/DIFO3kXKLv8oKrqqKh3asn2+elWHDBfi5KZ9Sf2JSDQTPJu3Vr2zhXDASiOu1LV16IZHjMSjpBEwGvD96Szkii3y9QZFdT3yeblCLIoeVE3v1/B0kVnni2mwcmy1zBKx27851urTl+9k9NzUYuSegAfb8XcrwIeOanVYM0eudkoM+/TqDGdJjR+EoSusZcilPAJGXQIfbwyWwLFFiBi53CdyY0zqItDb+t3lgpApH4EVwqSIQf9LHND17q0QcrOZFssL6FYe3cNgb1ymVJw2d5ehOzGjuXvJqJl1FLjsmjh2jpMo/2WKu8qlDfhN0alqbX3FzZnSg4GBWCIiqcQ/xhM9WEDenGUHiBenZCWnI0k88TplxLuCUjTbZAkQrSUyCDz1IrBkwvuU926KNyx1DNtGCYjEgpKGsSo3UfFVfG0Uo3+ApnI5gIlVqq14U1P7RTF5I87BJG3DHZK5X0lPo36abv5TPU3ldeWiBIqLNbdC9I9d+yndILe8u2y8hZo+cYWYeiwwCCVgjRSDHlxcb7fhjPYbZxQG6ALdRVutGea7y0FY+o8djLZJkhQF3V7y8/n4VIAugSbG6Ta7045TnVVUltQH6gB4oKtmluU8mXZVRG1Ttw2axBlQ4Phu+SKyRNQOBu0v3oWaTo1bdai4exFeMu8mZpM7nFDIXFTWCbipTHcQVbFmYz9FQSdfXkSWBlMePaD3Khw==
    template:
      metadata:
        name: thanos
        namespace: thanos
      type: Opaque
