global:
  leaderElection:
    namespace: "cert-manager"
crds:
  enabled: true
  keep: false
podDisruptionBudget:
  enabled: true
  minAvailable: 1
extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
resources:
  requests:
    cpu: "10m"
    memory: "128Mi"
    ephemeral-storage: "16Mi"
  limits:
    memory: "128Mi"
    ephemeral-storage: "16Mi"
webhook:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: "10m"
      memory: "128Mi"
      ephemeral-storage: "16Mi"
    limits:
      memory: "128Mi"
      ephemeral-storage: "16Mi"
cainjector:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: "10m"
      memory: "128Mi"
      ephemeral-storage: "16Mi"
    limits:
      memory: "128Mi"
      ephemeral-storage: "16Mi"
