{
 "title": "Compute / Cluster",
 "tags": [
  "prometheus",
  "talos",
  "cpu",
  "memory",
  "network",
  "performance",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},job)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Compute Cluster Health",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((1 - (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)) ^ 1.3) ^ (1/3) * 0.5 + \n( 1 - (1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) by (instance)) ^ 6) ^ (1/3) * 0.3 + \n(1 - max(rate(node_disk_io_time_seconds_total[$__rate_interval]))by (instance) ^ 1.1) ^ (1/2) * 0.2) * 100",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_min((1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)) * 100, 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_filesystem_avail_bytes) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "__auto"
    },
    { "expr": "node_netstat_Tcp_CurrEstab - 0", "legendFormat": "__auto" },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Traffic Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) + irate(node_network_receive_bytes_total{instance=~\".*\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Network Usage [30d]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Transmit Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Receive Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + sum(increase(node_network_receive_bytes_total{device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "30-Day Bandwidth"
    }
   ]
  },
  {
   "title": "Aggregate System Load [5m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (up == 1))",
     "legendFormat": "Active Instance(s)"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab)",
     "legendFormat": "All Connections"
    },
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]))) * 8",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "Aggregate Transmit Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8 + irate(node_network_receive_bytes_total{job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Established & TIME_WAIT Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{job=\"$job\"})",
     "legendFormat": "Current Established"
    },
    {
     "expr": "sum(node_sockstat_TCP_tw{job=\"$job\"})",
     "legendFormat": "TIME_WAIT"
    }
   ]
  }
 ]
}