{
 "title": "Compute / Nodes",
 "tags": [
  "prometheus",
  "talos",
  "cpu",
  "memory",
  "network",
  "performance",
  "nodes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},job)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "⏱️ Uptime"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", instance=\"$node\", mode='system'})",
     "legendFormat": "💎 Core(s)"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "🫙 Memory Total"
    },
    {
     "expr": "max(node_filesystem_size_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "💾 Disk Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + sum(increase(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Activity Analysis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", instance=\"$node\", mode='system'}) by (instance)",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\", instance=\"$node\",device!~'rootfs'} - node_filesystem_avail_bytes{job=\"$job\", instance=\"$node\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate",
   "type": "timeseries",
   "description": "Read + / Write -",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Network Bandwidth Usage",
   "type": "timeseries",
   "description": "Receive + / Transmit -",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Partition Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} \n- node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"})\n* 100 / node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Socket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_RetransSegs"
    },
    {
     "expr": "node_sockstat_sockets_used{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "sockets_used"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "TcpExt_ListenDrops"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "UDP_inuse"
    }
   ]
  }
 ]
}