autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "cert-manager-controller=quay.io/jetstack/cert-manager-controller:~v1"
workload:
  annotations:
    match-regex.version-checker.io/cert-manager-controller: 'v(\d+)\.(\d+)\.(\d+)'
  image:
    repository: "quay.io/jetstack/cert-manager-controller"
    tag: "v1.18.2"
  args:
  - '--v=2'
  - '--cluster-resource-namespace=$(POD_NAMESPACE)'
  - '--leader-election-namespace=$(POD_NAMESPACE)'
  - '--acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.16.2'
  - '--max-concurrent-challenges=60'
  probes:
    readinessProbe:
      path: "/livez"
      port: 9403
    livenessProbe:
      path: "/livez"
      port: 9403
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "128Mi"
        ephemeral-storage: "16Mi"
      limits:
        memory: "128Mi"
        ephemeral-storage: "16Mi"
service:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9402
  - name: healthz
    protocol: TCP
    port: 9403
rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
      - apiGroups:
        - cert-manager.io
        resources:
        - clusterissuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resourceNames:
        - issuers.cert-manager.io/*
        - clusterissuers.cert-manager.io/*
        resources:
        - signers
        verbs:
        - approve
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates
        - certificates/status
        - certificaterequests
        - certificaterequests/status
        verbs:
        - update
        - patch
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates
        - certificaterequests
        - clusterissuers
        - issuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates/finalizers
        - certificaterequests/finalizers
        verbs:
        - update
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - orders
        verbs:
        - create
        - delete
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
        - create
        - update
        - delete
        - patch
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - patch
      - apiGroups:
        - certificates.k8s.io
        resources:
        - certificatesigningrequests
        verbs:
        - get
        - list
        - watch
        - update
      - apiGroups:
        - certificates.k8s.io
        resources:
        - certificatesigningrequests/status
        verbs:
        - update
        - patch
      - apiGroups:
        - certificates.k8s.io
        resourceNames:
        - issuers.cert-manager.io/*
        - clusterissuers.cert-manager.io/*
        resources:
        - signers
        verbs:
        - sign
      - apiGroups:
        - authorization.k8s.io
        resources:
        - subjectaccessreviews
        verbs:
        - create
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges
        - challenges/status
        verbs:
        - update
        - patch
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - issuers
        - clusterissuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - patch
      - apiGroups:
        - ''
        resources:
        - pods
        - services
        verbs:
        - get
        - list
        - watch
        - create
        - delete
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingresses
        verbs:
        - get
        - list
        - watch
        - create
        - delete
        - update
      - apiGroups:
        - gateway.networking.k8s.io
        resources:
        - httproutes
        verbs:
        - get
        - list
        - watch
        - create
        - delete
        - update
      - apiGroups:
        - route.openshift.io
        resources:
        - routes/custom-host
        verbs:
        - create
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges/finalizers
        verbs:
        - update
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - clusterissuers
        - clusterissuers/status
        verbs:
        - update
        - patch
      - apiGroups:
        - cert-manager.io
        resources:
        - clusterissuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
        - create
        - update
        - delete
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - patch
      - apiGroups:
        - cert-manager.io
        resources:
        - issuers
        - issuers/status
        verbs:
        - update
        - patch
      - apiGroups:
        - cert-manager.io
        resources:
        - issuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
        - create
        - update
        - delete
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - patch
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - orders
        - orders/status
        verbs:
        - update
        - patch
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - orders
        - challenges
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - clusterissuers
        - issuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges
        verbs:
        - create
        - delete
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - orders/finalizers
        verbs:
        - update
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - patch
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates
        - certificaterequests
        - issuers
        verbs:
        - create
        - delete
        - deletecollection
        - patch
        - update
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates/status
        verbs:
        - update
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges
        - orders
        verbs:
        - create
        - delete
        - deletecollection
        - patch
        - update
      - apiGroups:
        - cert-manager.io
        resources:
        - certificates
        - certificaterequests
        - issuers
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - acme.cert-manager.io
        resources:
        - challenges
        - orders
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resourceNames:
        - cert-manager
        resources:
        - serviceaccounts/token
        verbs:
        - create
      - apiGroups:
        - coordination.k8s.io
        resourceNames:
        - cert-manager-controller
        resources:
        - leases
        verbs:
        - get
        - update
        - patch
      - apiGroups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - create
grafana:
  dashboard:
    enabled: true
    dashboards:
    - name: cert-manager
      title: "Cert Manager"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/cert-manager-controller/dashboards/cert-manager.json"
      folder: "System"
