apiVersion: v1
data:
  ADMIN_PASSWORD: Y0Z3RHhtVjNOQWVzNmZ2Mm5Xc2o0cFd6cHRNZ041MnVWeUJteUdnY0VaWnB5VDBrNkM1TWRjTXRiTUxDVGk2Nw==
  ADMIN_USER: YWRtaW4=
  CLIENT_SECRET: SXJFVWF0QlAwVllqRmVKQ1k5VHd5Y25IcHFsZVNMTUk=
kind: Secret
metadata:
  name: grafana
  namespace: grafana
type: Opaque
