namespace: "argocd"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

extraObjects:
  - |
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: this
      namespace: argocd
    spec:
      syncPolicy:
        preserveResourcesOnDeletion: false
      generators:
        - git:
            files:
              - path: helm/charts/*/source.yaml
            repoURL: https://github.com/jamie-stinson/labops
            revision: initial
      goTemplate: true
      template:
        metadata:
          name: "{{ index .path.segments 2 }}"
        spec:
          ignoreDifferences:
            - group: admissionregistration.k8s.io
              kind: ValidatingWebhookConfiguration
              name: istio-validator-istio
              jsonPointers:
                - /webhooks/0/failurePolicy
            - group: admissionregistration.k8s.io
              kind: ValidatingWebhookConfiguration
              name: istiod-default-validator
              jsonPointers:
                - /webhooks/0/failurePolicy
          destination:
            name: "in-cluster"
            namespace: "{{ if .namespace }}{{ .namespace }}{{ else }}{{ index .path.segments 2 }}{{ end }}"
          project: "production"
          revisionHistoryLimit: 3
          syncPolicy:
            automated:
              prune: true
              allowEmpty: true
              selfHeal: true
            retry:
              backoff:
                duration: 5s
                factor: 2
                maxDuration: 5m
              limit: 3
      templatePatch: |
        {{- $appName := index .path.segments 2 -}}
        spec:
          syncPolicy:
            managedNamespaceMetadata:
              labels:
                istio.io/dataplane-mode: ambient
            syncOptions:
              - Validate=true
              - CreateNamespace=true
              - PrunePropagationPolicy=foreground
              - PruneLast=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=false
              - ApplyOutOfSyncOnly=false
          sources:
            {{- if .commonHelmLibrary.enabled }}
            - repoURL: "ghcr.io/jamie-stinson/common-helm-library"
              chart: "common-helm-library"
              targetRevision: "1.*.*"
              helm:
                releaseName: "{{ index .path.segments 2 }}"
                valueFiles:
                  - "$values/helm/charts/global-values.yaml"
                  - "$values/helm/charts/{{ index .path.segments 2 }}/values.yaml"
            {{- end }}
            - repoURL: "{{ .repository }}"
              chart: "{{ .chart }}"
              targetRevision: "{{ .version }}"
              helm:
                releaseName: "{{ index .path.segments 2 }}"
                valueFiles:
                  - "$values/helm/charts/global-values.yaml"
                  - "$values/helm/charts/{{ index .path.segments 2 }}/values.yaml"
            - repoURL: https://github.com/jamie-stinson/labops
              targetRevision: initial
              ref: values
              {{- if .installCRDs }}
              path: helm/charts/{{ index .path.segments 2 }}/crds
              {{- end }}
  - |
    apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: "production"
      namespace: argocd
    spec:
      sourceNamespaces:
        - "*"
      sourceRepos:
        - "*"
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - server: https://kubernetes.default.svc
          namespace: "*"
