autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "grafana=docker.io/grafana/grafana:~v12"
workload:
  annotations:
    match-regex.version-checker.io/grafana: '(\d+)\.(\d+)\.(\d+)'
  image:
    repository: "docker.io/grafana/grafana"
    tag: "12.1.1"
  envsSecret:
  - name: GF_SECURITY_ADMIN_USER
    secret: grafana
    key: ADMIN_USER
  - name: GF_SECURITY_ADMIN_PASSWORD
    secret: grafana
    key: ADMIN_PASSWORD
  - name: GF_DATABASE_HOST
    secret: grafana-postgres-app
    key: host
  - name: GF_DATABASE_NAME
    secret: grafana-postgres-app
    key: dbname
  - name: GF_DATABASE_USER
    secret: grafana-postgres-app
    key: username
  - name: GF_DATABASE_PASSWORD
    secret: grafana-postgres-app
    key: password
  - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    secret: grafana
    key: CLIENT_SECRET
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "512Mi"
        ephemeral-storage: "512Mi"
      limits:
        memory: "512Mi"
        ephemeral-storage: "512Mi"
  probes:
    readinessProbe:
      path: "/api/health"
      port: 3000
    livenessProbe:
      path: "/api/health"
      port: 3000
  storage:
  - name: config
    type: configMap
    mountPath: /etc/grafana
    configMapName: grafana
    # - name: data
    #   type: emptyDir
    #   mountPath: /var/lib/grafana
autoscaling:
  enabled: false
service:
  ports:
  - name: http
    protocol: TCP
    port: 3000
configMap:
  enabled: true
  configMaps:
  - name: "grafana"
    data:
      grafana.ini: |
        [analytics]
        check_for_updates = false
        [grafana_net]
        url = https://grafana.net
        [log]
        mode = console
        [server]
        root_url = "https://grafana.projectwhitebox.com"
        [database]
        type = postgres
        [auth]
        disable_login_form = true
        [auth.generic_oauth]
        enabled = true
        name = Pocket ID
        use_refresh_token = true
        allow_sign_up = true
        auto_login = false
        client_id = 2e8e6d8d-137f-4ec8-8d92-b0c39b405246
        scopes = openid email profile groups
        auth_url = https://auth.projectwhitebox.com/authorize
        token_url = https://auth.projectwhitebox.com/api/oidc/token
        api_url = https://auth.projectwhitebox.com/api/oidc/userinfo
        role_attribute_path = "'Admin'"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
  - host: grafana.projectwhitebox.com
    path: /
    pathType: "Prefix"
    tls:
      enabled: false
    backend:
      service:
        name: "grafana"
        port: 3000
grafana:
  folder:
    enabled: false
    folders:
    - name: "system"
      title: "System"
  dashboard:
    enabled: true
    dashboards:
    - name: kubernetes-global
      title: "Kubernetes / Global"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/kubernetes-global.json"
      folder: "System"
    - name: kubernetes-pods
      title: "Kubernetes / Pods"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/kubernetes-pods.json"
      folder: "System"
    - name: kubernetes-api-server
      title: "Kubernetes / API Server"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/kubernetes-api-server.json"
      folder: "System"
    - name: compute-cluster
      title: "Compute / Cluster"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/compute-cluster.json"
      folder: "System"
    - name: compute-nodes
      title: "Compute / Nodes"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/compute-nodes.json"
      folder: "System"
    - name: kubernetes-storage
      title: "Kubernetes / Storage"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/tmp/dashboards/kubernetes-storage.json"
      folder: "System"
extraObjects:
- |
  apiVersion: grafana.integreatly.org/v1beta1
  kind: Grafana
  metadata:
    name: grafana
    labels:
      dashboards: "grafana"
  spec:
    external:
      url: http://grafana.grafana.svc.cluster.local:3000
      adminUser:
        name: grafana
        key: ADMIN_USER
      adminPassword:
        name: grafana
        key: ADMIN_PASSWORD
- |
  apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    name: grafana
    namespace: grafana
  spec:
    encryptedData:
      ADMIN_PASSWORD: AgBzLGbP/pB3N0voEN0t05C5DYl8nhKqin1sSKItvbo01rpvp988xYvf/Yl7jo+mIA+fI5JBFgXlfiIDAvaz3vUU3RFeBsBrRctpKFjVLO9VsA41uk1COq619/LrR1KKqRufiJKP/qtfAVCAsh+eNPLu02Df/myoIHRP95sEBXjwsBwt1uuh1Bm/I0PdZpKOgC+CJFp3QQUPdtQLsaBGj/GMSM1v60rnPwISb5GbcdE1Y+eGBiB5+2vH1Z/0sS1HDdzBK3QCjP9ZRQmHeU/BDnaAZvzCFKJarUrxSspE+dnf4keUWWFqwwQftl9Zisc4BKKBA2F3z0o5z6eI0Tf6fw1YrksBi56/o/DQFM3nT2jrhjxMFYQP5cGEMoUykaHAveTPhJjH/wwb7VKd4S1AI/RhV+ARjn+6IbjDrn95CNb1fBaUfhkLb/zjmyhfiRdoVG50w+w5RCeZFf779Ehr+1WQhgoAXdE9GF8CTexlcy3hSqSkLzafu5eiJOrkC36H7ZlSXlUbhgwiBTELODAwSTJNg+mIbUOia7QQKwR8fYjPcxIA75G9YS/b/AJUgsu+bHteTr5YTX1Yfa2+aYBnMnQ38SX7HYfxUq+tCVaTAdoydiMdEcGpgB37FurU1ZcVJuGua7BVnBfhHTsLkGnIrKAdNbTpfh0MiDrEwN5qsp8jzEH4uzHr0/KhqXsmMzSULKxlnvg/XIwcUYKQv2uiRbJyLLlBvPWSKmzYMXJTOXm0bQRD0amhqdlcqmYkl6elRM1JO1hY1wDpdWeMgCtTXKox
      ADMIN_USER: AgAExvO6EJQ750KubmHP++JYKSbmijKwAwg3fTh4l077lWFbpESi4sQmTAb7ajwRqtM19k04GENRv2imUjU/11t2dCserdOzYX9nNM95gJ/n6iOlpTMWPhf4R4RRyshnGvUHK3S3AYBx3+t8wL+3qvo7Xg9rwnbunzXucdTVYbZmETaMEsJUOuq67HcFkb+ijsOSHqrwirln0NQB66Wl4lSnlwXn8Rka7WHU9wnqX3bS5nETnxbuDFwZNDf53gZsHazS7UYEIVtzFiU05C575blZwAbMn4ojBJTt+2ho7JCCbW5uPGFNq30JtYwaCGswbmHWCQvpjxSZdq/DHPWm1NGPyEHO0rj5HHUrNOhJ5ANOIqMtv2feBT7Td6VdZjW5KDcuhe1ODsg4XZSaTrbKciSCjZCKA04CgGWnlsV5dyKlo3qjWeVeoZGadcF3CI/TU8d4k6MWiJcAlNNeNWm1yIIkkxNg7AMwtQ72vT9mLCeUbwnEuJm2bbDbOqk8u/bjhvct9MUWkIEBi363NtqGuMZXd+uXTtPawnNMZkk0+unjWxqgYgls9QGzDQctdeZ1p8ajNF74+Xc//gVmRonG1IELQDCLUqnW8mBx8E3zcP+m4wUWlhv81Kl444rDHXuEnIYjju6sSeRUx8E+V9NNYndabCAFpuVy5y7dEaRJ3IZTBWhVa6002BGlafo4oQy41HlAfFbk2Q==
      CLIENT_SECRET: AgB6kWHB1SJVhzT4wuJWynCM1gkqW8JMd70TOnVVsaGidmUJffYYA5Bhtmh8lRwsm5dh4vqJex6l5pcXBZGCQoF13VHQ9fcKQMGtgvlV9uZ5c7Lt0FNa4i6cfSCex/EOBIa5qHHyBNuud8ouLvNzpauf9lpYGcqbyR1twhRlxXvyvUETbpN+ViFjLJ27xGwNhk2wcGL5aBfkyensyLLZ3OScL4d2YS+3r5ak1juTUeySUaJl6h0gVSUuqSSeJiS6ifD59BAiMPjbhmBJThIly/1XEYXqSQEX3BG0S/Qswr0Tyw7lopujPdDKNmL3pLR+otBUeUy21FQPoWaUMvGYB/63Bw30iIvEiolI3ImqBWXokHof5X/oL3KHaxKtRYN+aS7cb6PWBD/J4vu8j3A/RqtiYzz9RtzYtTaByc25SfbXWsCqd+4Gfg+mEKVA1e/AYSrCGCgZ13t60PrgGRX475yimot1G+2rc3GYfec2pg7J6pzvohsNPwFTJQNTNL2h1xymfyJAX1M1zBZFoPaotiuHsRyT8dBTVE4ZPTxiIWXNqKcrOd6KVB84yEsx29t4MIPSJ/4Pdz62VzylHDjFhWKHsCpE+MXFm/jJ1p7xPM148/nfut24S7c+vktETntkqbk+mK1L7KsOryhs1HOvkavRAhPw+DGt8X/YtOQAMhPafyZ0BQLLb1dI9cxoY6lh0L+LOS6/fKieuGyo4jXQmxjm0/gqFNFq8S5sv5O0NrvDXQ==
    template:
      metadata:
        name: grafana
        namespace: grafana
      type: Opaque
