autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "grafana=docker.io/grafana/grafana:~v12"
workload:
  annotations:
    match-regex.version-checker.io/grafana: '(\d+)\.(\d+)\.(\d+)'
  image:
    repository: "docker.io/grafana/grafana"
    tag: "12.1.1"
  envs:
    - name: GF_INSTALL_PLUGINS
      value: "victoriametrics-metrics-datasource 0.18.3,victoriametrics-logs-datasource 0.19.3"
  envsSecret:
  - name: GF_SECURITY_ADMIN_USER
    secret: grafana
    key: ADMIN_USER
  - name: GF_SECURITY_ADMIN_PASSWORD
    secret: grafana
    key: ADMIN_PASSWORD
  - name: GF_DATABASE_HOST
    secret: grafana-postgres-app
    key: host
  - name: GF_DATABASE_NAME
    secret: grafana-postgres-app
    key: dbname
  - name: GF_DATABASE_USER
    secret: grafana-postgres-app
    key: username
  - name: GF_DATABASE_PASSWORD
    secret: grafana-postgres-app
    key: password
  - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    secret: grafana
    key: CLIENT_SECRET
  resources:
    preset: ""
    custom:
      requests:
        cpu: "10m"
        memory: "2Gi"
        ephemeral-storage: "10Gi"
      limits:
        memory: "2Gi"
        ephemeral-storage: "10Gi"
  probes:
    readinessProbe:
      path: "/api/health"
      port: 3000
    livenessProbe:
      path: "/api/health"
      port: 3000
  storage:
  - name: config
    type: configMap
    mountPath: /etc/grafana
    configMapName: grafana
    # - name: data
    #   type: emptyDir
    #   mountPath: /var/lib/grafana
autoscaling:
  enabled: false
service:
  ports:
  - name: http
    protocol: TCP
    port: 3000
configMap:
  enabled: true
  configMaps:
  - name: "grafana"
    data:
      grafana.ini: |
        [analytics]
        check_for_updates = false
        [grafana_net]
        url = https://grafana.net
        [log]
        mode = console
        [server]
        root_url = "https://grafana.projectwhitebox.com"
        [database]
        type = postgres
        [auth]
        disable_login_form = true
        [auth.generic_oauth]
        enabled = true
        name = Pocket ID
        use_refresh_token = true
        allow_sign_up = true
        auto_login = false
        client_id = 2e8e6d8d-137f-4ec8-8d92-b0c39b405246
        scopes = openid email profile groups
        auth_url = https://auth.projectwhitebox.com/authorize
        token_url = https://auth.projectwhitebox.com/api/oidc/token
        api_url = https://auth.projectwhitebox.com/api/oidc/userinfo
        role_attribute_path = "'Admin'"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
  - host: grafana.projectwhitebox.com
    path: /
    pathType: "Prefix"
    tls:
      enabled: false
    backend:
      service:
        name: "grafana"
        port: 3000
  folder:
    enabled: false
    folders:
    - name: "system"
      title: "System"
extraObjects:
- |
  apiVersion: grafana.integreatly.org/v1beta1
  kind: Grafana
  metadata:
    name: grafana
    labels:
      dashboards: "grafana"
  spec:
    external:
      url: http://grafana.grafana.svc.cluster.local:3000
      adminUser:
        name: grafana
        key: ADMIN_USER
      adminPassword:
        name: grafana
        key: ADMIN_PASSWORD
- |
  apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    name: grafana
    namespace: grafana
  spec:
    encryptedData:
      ADMIN_PASSWORD: AgBzLGbP/pB3N0voEN0t05C5DYl8nhKqin1sSKItvbo01rpvp988xYvf/Yl7jo+mIA+fI5JBFgXlfiIDAvaz3vUU3RFeBsBrRctpKFjVLO9VsA41uk1COq619/LrR1KKqRufiJKP/qtfAVCAsh+eNPLu02Df/myoIHRP95sEBXjwsBwt1uuh1Bm/I0PdZpKOgC+CJFp3QQUPdtQLsaBGj/GMSM1v60rnPwISb5GbcdE1Y+eGBiB5+2vH1Z/0sS1HDdzBK3QCjP9ZRQmHeU/BDnaAZvzCFKJarUrxSspE+dnf4keUWWFqwwQftl9Zisc4BKKBA2F3z0o5z6eI0Tf6fw1YrksBi56/o/DQFM3nT2jrhjxMFYQP5cGEMoUykaHAveTPhJjH/wwb7VKd4S1AI/RhV+ARjn+6IbjDrn95CNb1fBaUfhkLb/zjmyhfiRdoVG50w+w5RCeZFf779Ehr+1WQhgoAXdE9GF8CTexlcy3hSqSkLzafu5eiJOrkC36H7ZlSXlUbhgwiBTELODAwSTJNg+mIbUOia7QQKwR8fYjPcxIA75G9YS/b/AJUgsu+bHteTr5YTX1Yfa2+aYBnMnQ38SX7HYfxUq+tCVaTAdoydiMdEcGpgB37FurU1ZcVJuGua7BVnBfhHTsLkGnIrKAdNbTpfh0MiDrEwN5qsp8jzEH4uzHr0/KhqXsmMzSULKxlnvg/XIwcUYKQv2uiRbJyLLlBvPWSKmzYMXJTOXm0bQRD0amhqdlcqmYkl6elRM1JO1hY1wDpdWeMgCtTXKox
      ADMIN_USER: AgAExvO6EJQ750KubmHP++JYKSbmijKwAwg3fTh4l077lWFbpESi4sQmTAb7ajwRqtM19k04GENRv2imUjU/11t2dCserdOzYX9nNM95gJ/n6iOlpTMWPhf4R4RRyshnGvUHK3S3AYBx3+t8wL+3qvo7Xg9rwnbunzXucdTVYbZmETaMEsJUOuq67HcFkb+ijsOSHqrwirln0NQB66Wl4lSnlwXn8Rka7WHU9wnqX3bS5nETnxbuDFwZNDf53gZsHazS7UYEIVtzFiU05C575blZwAbMn4ojBJTt+2ho7JCCbW5uPGFNq30JtYwaCGswbmHWCQvpjxSZdq/DHPWm1NGPyEHO0rj5HHUrNOhJ5ANOIqMtv2feBT7Td6VdZjW5KDcuhe1ODsg4XZSaTrbKciSCjZCKA04CgGWnlsV5dyKlo3qjWeVeoZGadcF3CI/TU8d4k6MWiJcAlNNeNWm1yIIkkxNg7AMwtQ72vT9mLCeUbwnEuJm2bbDbOqk8u/bjhvct9MUWkIEBi363NtqGuMZXd+uXTtPawnNMZkk0+unjWxqgYgls9QGzDQctdeZ1p8ajNF74+Xc//gVmRonG1IELQDCLUqnW8mBx8E3zcP+m4wUWlhv81Kl444rDHXuEnIYjju6sSeRUx8E+V9NNYndabCAFpuVy5y7dEaRJ3IZTBWhVa6002BGlafo4oQy41HlAfFbk2Q==
      CLIENT_SECRET: AgB6kWHB1SJVhzT4wuJWynCM1gkqW8JMd70TOnVVsaGidmUJffYYA5Bhtmh8lRwsm5dh4vqJex6l5pcXBZGCQoF13VHQ9fcKQMGtgvlV9uZ5c7Lt0FNa4i6cfSCex/EOBIa5qHHyBNuud8ouLvNzpauf9lpYGcqbyR1twhRlxXvyvUETbpN+ViFjLJ27xGwNhk2wcGL5aBfkyensyLLZ3OScL4d2YS+3r5ak1juTUeySUaJl6h0gVSUuqSSeJiS6ifD59BAiMPjbhmBJThIly/1XEYXqSQEX3BG0S/Qswr0Tyw7lopujPdDKNmL3pLR+otBUeUy21FQPoWaUMvGYB/63Bw30iIvEiolI3ImqBWXokHof5X/oL3KHaxKtRYN+aS7cb6PWBD/J4vu8j3A/RqtiYzz9RtzYtTaByc25SfbXWsCqd+4Gfg+mEKVA1e/AYSrCGCgZ13t60PrgGRX475yimot1G+2rc3GYfec2pg7J6pzvohsNPwFTJQNTNL2h1xymfyJAX1M1zBZFoPaotiuHsRyT8dBTVE4ZPTxiIWXNqKcrOd6KVB84yEsx29t4MIPSJ/4Pdz62VzylHDjFhWKHsCpE+MXFm/jJ1p7xPM148/nfut24S7c+vktETntkqbk+mK1L7KsOryhs1HOvkavRAhPw+DGt8X/YtOQAMhPafyZ0BQLLb1dI9cxoY6lh0L+LOS6/fKieuGyo4jXQmxjm0/gqFNFq8S5sv5O0NrvDXQ==
    template:
      metadata:
        name: grafana
        namespace: grafana
      type: Opaque
- |
  apiVersion: grafana.integreatly.org/v1beta1
  kind: GrafanaDashboard
  metadata:
    name: kubernetes-pods
    namespace: grafana
  spec:
    allowCrossNamespaceImport: true
    contentCacheDuration: 1h
    folder: System
    instanceSelector:
      matchLabels:
        dashboards: grafana
    resyncPeriod: 1m
    gzipJson: |-
      H4sIAGfbumgAA+1dUXPbNhJ+96/g8TI3yY3kWrbk2jfTB9tNZjJter46zc1d4tFAJCShhggGBG0rHt1vvwVIggQFypaiWFKLzqQSgSWw2F3sfh8kUw97nuejKGICCcKixP+H9wBN0EhJIuDqo7ry8lbVM0gJFW8j6Oy0ytYQCZSwlAdYj5H3iGks26oSrWp/SkLZPeJoiCLk665ZZXQcoQGVowie4kr7mISWVhKw6IJRxuW4fDRALw9a3mGnA//r9Vpe51VFAT9CE6XeWWkF72/eGcVcJFU5gfgIi/riKJkQ2dg5ODAWNUEiGJ9FU+gaIppgo1OgkbT0x+uW3U7JeMAQD+2maBSbqdfrvVzcxyERudW0Cv6QJAGi/8GIX8GCxDsWiTEIKOWlC+Lxe8aoILFuVN45UW8piW5Kxf0YRZgmOkgKuzSFgtb8lgSCcQJ2F5wESbt4tQZIER4vHsrumV5yS8+Jk4CTWLpPSl+y0Lu4/M1LEzTCHscUHHuLPcE8IhK4zsaBN59TnIhkX08IBsI0vGDRkIxM7UM8RCkVST0CgjzQqo0yAJiKTF+MYbYxo2HiVwRmhueDNBFsMj8GuifJOeMh5ldjdmcLpVzoAkcCcxz+F3O2SEyq+q5QDN8L3yL0MxpgqmyIwUSRVeaSogBPZCfIoVQwm9AVG4p36N7ME2YviYowq/QOED+jZBTl41u6/01CMX6DZBRJgf3jmkjI0d2VmKrQl0GL6+oNCaX/jFFAxFTt3Vo37IOQwOyFqZJgDKutDyJzzxtu8ZvcKXiEo9DuCrkT9B6z99+SL0Wf0TWrqUCiBNLULylV29Dmdrn6tzI4YkZRsTuSCWOw7S2iyrIgcljrixmJxBX5Is3Rq/XJhIJ/hHLBySDNp5gzSLH35SSI+wtXBdvl7lJOKBflR/gW87quCeSeRctOBApuSDSyqTLiLI1VxvfnDF/s2ohB0CxUstzXRaTNTVQMxobD2liNmWCC4hjUtlWHMo805po427GQ8ubsJXBcZuryv7rOlXwGdsI4mjORjE5EUznfQa1rVpddNPpfX5+dnxydLhq/91UTQDpcNPhprz64cX3d6KI0UgW/MLa6tBZqBnHLIUdkzpyrWCPou2SmN/1xUWvza5n0O5XN6N+bGdGfVvxQjq1KZk/L+Sw20Z1q1DnKLGeIBpbwC0kSUzQtMqJCh4ZAXC0JAyZkQTME5K7+2UiLdnijU6Ohlky2srpZN7zeABMo0KQ2LeNKJQkQKn6aM1lM0xGJPmCe5Emyc7jf2e+UwCDDf+YmMlRsRMCrQh915yL4U7NdjvnKEh/IV7P/Hk/AU3wOM6u+WG2cJJ285Ejgl4CiBYJ8zftBnPYVlOonGFrDpC8AK9MHiZ0hFQf4h0/+C33xyW95MQt/+B80wqu8JBO4+S8gJS8CCngHc3lP/vaTP/v4ot+Xs/aJrFawS69fvfIGU+8ljPDK+86TWt2kA9yH636pWQHl+gWUe7pOxa0gB+uTLb+zgRKA10Y9S6VMyxZqK2fJoWlWCw2hbMu9YRzogRR8eJBKebOZKcZRNJqnNbIDD9+GWemaC+XrMlKJyKBPgYJ/S6olQQejIGAczAnOoWkeStuG49/hCePTDUL5IbnHoeaTA1k/apvUgX0H9ncP7DcCV2kxdSujJFwMgx1pcKRhq0jD93O4fo2k4WR3SYPRsIA1HH1D1pAdRzbTBk5GY+FYQ7mqHWMNJSyfKMzWv2NcJlRgDaI/mAq8BDp/nDE8Hz3IVrNOhrBxWpCD6h1iBus+mI8BgAiB2wFFSUKCXQPsktddMAjSlSD79sFulov+CXC3w8ubxcshDqC6qGV11wik0UAd+uwAjH4M5c4NviTKNR27kTPxEzu6PTx1Z+IO3W7jmXgx7mqH5Pp2NQuMvd7j6Ta801N8M1x6oWfYsUNrB00NaHoumZ6DpbsGS91x8B8O3houcPB2TfBWnWRt+vi2AeD29MdvDuA6gJv3b/z49kngdgUku6Xw1R2u7jiCdeB118CrA527/B0Ehy01tiTRefzc4LJ+eNo5toPLoy0Gl7J6Pyu2rB1yO2y5zOFphIUEl32OA0xucYYulz1AffIR6RqOQn/NFA2/Bjq2/thubnsLHC3AVMmEiO339PtcU7G8s8+f/PWLcxSFdwqyOHrg6IHn6IGjB5mIoweWiRw90N8ffnZuMHfw3EgO9HdpHDlw5CDrXw85gDJ1A7bYZtDo6MGa6MEO+PpZCMKlsoP3KxLuEwRHEXS3owiFnKMIjiI4ilAZYHMUof7xwWG3gSHobOUYgmMIWf96GULIWRzjcJvRo2MKa2YKO+DzZ2QMifdjZg/HGhxrKLodayjkHGtwrMGxhsoAW/TBQiNt+N7RBkcbvgVtgMhmfKvPmh1bWBNb2H5XPwtJ+CWzi/dameMJHGEvH8qPOaYMGQhNKiBrrLyxlw2WPT0Plfmnq74yqp94rwb15YN6OLhI/5UojM4gtsY4LVswH0rbRDrG5FM6i7fZH6gUV7m39a0se/5iprhQISSq2GbBjxsEKedZ8jc2i0LulQ1R7ATTU0U19ocBOjgcnobt487xabs7CLrt02532A6OuydB2B10USewl9v8Bw2qtZFEEHshPlN/hFkrGvrXC+wkrKyX1TLof04xny5P6Up3d4zWEb6vkRfbbz7US9XTjd5gZLsBH/8diiWT2iMpzZgbDwngqbzyUsnq+krdJHs2VQQJDrLGkLXybGL8EMWqrs/HWsLvhlk+8+n7zDLGkzvLIFlyHdXEdKm39QcEFh9Q/C856muV9ttGm92iS4RcjpA6lij8XJ1ghQCUi24nU1jppCEWqxI7F5bykWnSmw/WctfydIU0wvVJsalvXTk6m6NwJbXt0dnWsjoo25uPSkTphyLA9v9eHfWReJU+scapyWd9ADIwRxWeXe9u8DaDuob4qD2hzwzo2i8KZYxsrrkIcxjqWwb41y6tIehBaslwP9xgEj46aEJbsseq+JNSlBWfV11YmbNGkxJMcSDxuv1MrdC8M/cwFK16p/lB4SvO1VswWW+V2eq0Y4FLGp2ynqVNmlc2WfNcR81zHa17rl7zXD1zLv3eCuY7ScsDF7c8MD28m8Ab+GeMrjdj/vHHyruxVkgU/BkLEbeBPEItwIbvr63bdrkh/jx16Xc2+Cpa8EipguGfkSmsywpbTyrUa/nbe/IcpTxuGGYfevkRu2t39Ib0BcsbfeO+mAQ3WH3GWbZ9kce+hW7lkc5P+iDF+867lMceqj+P4vKYpR/rvlt9NHO0N9v7P4s+eh8AcgAA
